import localFont from 'next/font/local';
import './globals.css';

import { Navbar } from '../components';

const aeonik = localFont({
	src: '../assets/fonts/aeonik/AeonikTRIAL-Regular.otf',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={aeonik.className}>
				<div>{children}</div>
			</body>
		</html>
	);
}
