// VIDEOS USED AFTER THE HERO ANIMATION
export const scrollVideos = [
	{
		video: '/videos/2.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'square',
	},
	{
		video: '/videos/4.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'landscape',
	},
	{
		video: '/videos/5.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'portrait',
	},
	{
		video: '/videos/6.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'square',
	},
	{
		video: '/videos/10.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'square',
	},
	{
		video: '/videos/2.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'portrait',
	},
	{
		video: '/videos/4.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'square',
	},
	{
		video: '/videos/5.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'landscape',
	},
	{
		video: '/videos/6.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'square',
	},
	{
		video: '/videos/10.mp4',
		title: 'Don Chandelier',
		desc: 'Emoticon',
		link: '#',
		type: 'portrait',
	},
];
